name: Auto Merge PRs from bots

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: |
      (
        startsWith(github.event.pull_request.head.ref, 'release-please--branches--main--components') ||
        startsWith(github.event.pull_request.head.ref, 'automated-documentation-update-') 
      )

    runs-on: ubuntu-latest

    steps:
      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          gh pr merge \
            --repo "${{ github.repository }}" \
            --squash \
            --delete-branch \
            "${{ github.event.pull_request.number }}"
