name: "Release Features"

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}

    steps:
      - name: Create release(s)
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: .release-please-config.json
          include-component-in-tag: true
          disable-repo-tagging: true

      - name: Debug release outputs
        run: |
          echo "releases_created=${{ steps.release.outputs.releases_created }}"
          echo "paths_released=${{ steps.release.outputs.paths_released }}"

  publish:
    runs-on: ubuntu-latest

    needs: release

    if: needs.release.outputs.releases_created == 'true'

    steps:
      - uses: actions/checkout@v6

      - name: "Publish all features from ./src"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        uses: devcontainers/action@v1

        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "true"

      - name: Create PR for Documentation
        id: push_image_info

        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}

        run: |
          set -e
          echo "Start."
          # Configure git and Push updates
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git config pull.rebase false
          branch=automated-documentation-update-$GITHUB_RUN_ID
          git checkout -b $branch

          # Add / update and commit
          git add */**/README.md
          git commit -m 'docs: regenerate feature documentation [skip ci]' || export NO_UPDATES=true

          # Push
          if [ "$NO_UPDATES" != "true" ] ; then
              git push origin "$branch"
              gh pr create --title "docs: update generated feature documentation" --body "Automated documentation update"
          fi
